## MyToDoReact version 1.0.
##
## Copyright (c) 2021 Oracle, Inc.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
apiVersion: v1
kind: Service 
metadata:
  name: todolistapp-helidon-se-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    #targetPort: 80
    targetPort: 8080
  selector:
    app: todolistapp-helidon-se
---
kind: Deployment
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
metadata:
  name: todolistapp-helidon-se-deployment
spec:
#Added on 08/07/2020
  selector:
    matchLabels:
      app: todolistapp-helidon-se
#End added
  replicas: 2
  template:
    metadata:
      labels:
        app: todolistapp-helidon-se
        version: v1
    spec:
      containers:
      - name: todolistapp-helidon-se
        image: %DOCKER_REGISTRY%/todolistapp-helidon-se:0.1
        imagePullPolicy: Always
        env:
        - name: database.user
          value: "TODOUSER"
        - name: database.url
          value: "jdbc:oracle:thin:@%TODO_PDB_NAME%_tp?TNS_ADMIN=/mtdrworkshop/creds"
        - name: todo.table.name
          value: "todoitem"
        - name: OCI_REGION
          value: "%OCI_REGION%"
        - name: dbpassword
          valueFrom:
            secretKeyRef:
              name: dbuser
              key: dbpassword
              optional: true
        volumeMounts:
        - name: creds
          mountPath: /mtdrworkshop/creds
        ports:
        - containerPort: 8080
        ## if you want to use a livenessProbe or readinessProbe, need to add a handler to the code -petersong
        # livenessProbe:
        #   httpGet:
        #     path: /heath/live
        #     port: 8080
        #   initialDelaySeconds: 220
        #   periodSeconds: 3
        # readinessProbe:
        #   httpGet:
        #     path: /health/ready
        #     port: 8080
        #   initialDelaySeconds: 40
        #   periodSeconds: 3
      restartPolicy: Always
      volumes:
      - name: creds
        secret:
          secretName: db-wallet-secret
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: todolistapp-helidon-se
---